# Git
alias ga="git add"
alias gaa="git add ."
alias gau="git add -u"
alias gb="git branch -a"
alias gbd="git branch -D"
alias gsw="git switch -c $@"
alias gc="git commit"
alias gcm="git commit -m"
alias gcma="git commit -am"
alias gcmp"git commit -m $@ && git push"
alias gca="git commit --amend --no-edit"
alias gcaa="git commit -a --amend --no-edit"
alias gcam="git commit --amend -m"
alias grn="git commit --amend"
alias gcap="git commit --amend --no-edit && git push --force"
alias gcaap="git commit -a --amend --no-edit && git push --force"
alias gcamp="git commit --amend && git push --force"
alias gcamap="git commit -a --amend && git push --force"
alias gch="git checkout"
alias gchf="git checkout --force"
alias gcho="git checkout --orphan"
alias gcl="git clone"
alias gd="git diff --color=always"
alias gds="git diff --color=always --staged"
alias gdsa="git add . && git diff --color=always --staged"
alias gf="git fetch"
alias gfa="git fetch --all"
alias gl="git log --oneline --decorate --graph"
alias glf="git log -p -- $@"
alias gls="git ls-files --full-name | awk -F/ "\""{print $1}"\"" | sort -u"
alias gp="git push"
alias gpf="git push --force"
alias gpl="git pull"
alias gplf="git pull --force"
alias grm"git rm -f --cached"
alias grma"git rm . -r"
alias gs="git status"
alias gsh="git show --color=always"
alias gst="git stash"
alias gsta="git stash apply"
alias gstd="git stash drop"
alias gstc="git stash clear"
alias gstl="git stash list"
alias gstad="git stash apply && git stash drop"
alias grb="git rebase"
alias grbi="git rebase -i"
alias grbir="git rebase -i --root"
alias grbc="git rebase --continue"
alias grbs="git rebase --skip"
alias grba="git rebase --abort"
alias grs="git reset"
alias gdl="git reset --hard HEAD^"
alias gun="git reset --hard HEAD"
alias grm="git rm --cached -r $@"
alias grma="git rm --cached -r ."
alias greset="git fetch --all & git reset --hard origin/main"
# TODO: Figure out local gitignore
# alias gig="git update-index --assume-unchanged $@"
# alias gigr="git update-index --no-assume-unchanged $@"
